apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - model-deployment.yaml
  - model-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-service-lb.yaml
  - streamlit-deployment.yaml
  - streamlit-service-lb.yaml
