apiVersion: v1
kind: Service
metadata:
  name: model-service
  namespace: house-price-predictor
  labels:
    app: model-service
spec:
  type: ClusterIP
  selector:
    app: model-service
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
