apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-lb
  namespace: house-price-predictor
  labels:
    app: streamlit-app
spec:
  type: LoadBalancer
  selector:
    app: streamlit-app
  ports:
  - name: http
    port: 80
    targetPort: 8501
    protocol: TCP
